version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql-hangfire
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hangfire_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
